### PR TITLE
Explicitly activate CSRF protection. Fixes #101

### LINKED ISSUE #101: Explicitly activate CSRF protection as requested from Octoprint 1.8.3
From 1.8.3 on, Octoprint asks plugins to explicitly activate CSRF protection (or not).

See https://octoprint.org/blog/2022/09/20/new-release-1.8.3/

### PR DESCRIPTION
**Pull request by WildRikku**
It's a small fix but I wanted to start somewhere before I contribute something bigger.

### CODE REVIEW

**Comment by guysoft** [comment]
Hey, thanks for sharing! can you give an example or point to the docs where it says that ``is_blueprint_csrf_protected`` returning true is the method that activates it?

**Comment by WildRikku** [comment]
Sure! https://docs.octoprint.org/en/1.10.2/plugins/mixins.html#octoprint.plugin.BlueprintPlugin.is_blueprint_csrf_protected

**Comment by guysoft** [comment]
Ok, thanks, merging

**Comment by guysoft** [comment]
I still need to make a new release, but can't do that right now, will happen later

**Pull request merged**
